CREATE DATABASE EMPRESAXYZ;

CREATE TABLE USUARIO
(
	CD_USUARIO INT PRIMARY KEY IDENTITY NOT NULL,
	NM_NOME VARCHAR(50) NOT NULL,
	NM_SOBRE_NOME VARCHAR(100),
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DH_NASCIMENTO DATE NOT NULL,
	CD_STATUS INT NOT NULL,
	DH_TIMESTAMP DATETIME DEFAULT GETDATE()
)

CREATE TABLE USUARIO_TELEFONE
(
	CD_USUARIO_TELEFONE INT PRIMARY KEY IDENTITY NOT NULL,
	CD_USUARIO INT NOT NULL,
	FOREIGN KEY (CD_USUARIO) REFERENCES USUARIO(CD_USUARIO),
	DDD VARCHAR(2) NOT NULL,
	TELEFONE VARCHAR(9) NOT NULL,
	CD_STATUS INT NOT NULL,
	DH_TIMESTAMP DATETIME DEFAULT GETDATE()
)

CREATE PROCEDURE INSERIR_USUARIO_E_TELEFONE
	@NM_NOME VARCHAR(50),
	@NM_SOBRE_NOME VARCHAR(100),
    @CPF VARCHAR(11),
	@EMAIL VARCHAR(100),
    @DH_NASCIMENTO DATE,
	@DDD VARCHAR(2),
    @TELEFONE VARCHAR(9)
AS
BEGIN
    -- Verifica se o usuário tem pelo menos 18 anos
    IF DATEDIFF(YEAR, @DH_NASCIMENTO, GETDATE()) < 18
    BEGIN
        PRINT 'Usuário deve ter pelo menos 18 anos.';
        RETURN;
    END
    
    -- Verifica se o CPF já está cadastrado
    IF EXISTS (SELECT 1 FROM USUARIO WHERE CPF = @CPF)
    BEGIN
        PRINT 'CPF já cadastrado.';
        RETURN;
    END

    -- Inserindo o novo usuário
    INSERT INTO USUARIO (NM_NOME, NM_SOBRE_NOME, CPF, EMAIL, DH_NASCIMENTO, CD_STATUS)
    VALUES (@NM_NOME, @NM_SOBRE_NOME, @CPF, @EMAIL, @DH_NASCIMENTO, 1);

    -- Inserindo o telefone do usuário
    DECLARE @IDUsuario INT;
    SET @IDUsuario = SCOPE_IDENTITY(); -- Obtém o ID do usuário inserido

    INSERT INTO USUARIO_TELEFONE (CD_USUARIO, DDD, TELEFONE, CD_STATUS)
    VALUES (@IDUsuario, @DDD, @TELEFONE, 1);
END;


CREATE PROCEDURE CONSULTAR_TODOS_USUARIOS_COM_TELEFONE
	AS
BEGIN 
	
	SELECT US.CD_USUARIO, NM_NOME, NM_SOBRE_NOME, CPF, DDD, TELEFONE, EMAIL, DH_NASCIMENTO, US.CD_STATUS FROM USUARIO AS US
	INNER JOIN USUARIO_TELEFONE AS UT ON UT.CD_USUARIO = US.CD_USUARIO WHERE CD_STATUS = 1;
END;


CREATE PROCEDURE CONSULTAR_USUARIO_COM_TELEFONE

@CD_USUARIO INT
AS

BEGIN 

	SELECT US.CD_USUARIO, NM_NOME, NM_SOBRE_NOME, CPF, DDD, TELEFONE, EMAIL, DH_NASCIMENTO, US.CD_STATUS FROM USUARIO AS US
	INNER JOIN USUARIO_TELEFONE AS UT ON UT.CD_USUARIO = @CD_USUARIO
	WHERE US.CD_USUARIO = @CD_USUARIO;
END;


CREATE PROCEDURE ATUALIZAR_USUARIO
	@CD_USUARIO INT,
	@NM_NOME VARCHAR(50),
	@NM_SOBRE_NOME VARCHAR(100),
	@CPF VARCHAR(11),
	@EMAIL VARCHAR(100),
	@DH_NASCIMENTO DATE,
	@DDD VARCHAR(2),
	@TELEFONE VARCHAR(9)

AS

BEGIN
	UPDATE USUARIO
	SET NM_NOME = @NM_NOME, NM_SOBRE_NOME = @NM_SOBRE_NOME, CPF = @CPF, EMAIL = @EMAIL, DH_NASCIMENTO = @DH_NASCIMENTO
	WHERE CD_USUARIO = @CD_USUARIO;

	UPDATE USUARIO_TELEFONE
	SET DDD = @DDD, TELEFONE = @TELEFONE
	WHERE CD_USUARIO = @CD_USUARIO
END;

CREATE PROCEDURE DESATIVAR_USUARIO

 @CD_USUARIO INT
AS
BEGIN

    UPDATE USUARIO
    SET CD_STATUS = 0
    WHERE CD_USUARIO = @CD_USUARIO;


    UPDATE USUARIO_TELEFONE
    SET CD_STATUS = 0
    WHERE CD_USUARIO = @CD_USUARIO;
END;

CREATE PROCEDURE EXCLUIR_USUARIO_E_TELEFONE

@CD_USUARIO INT

AS

BEGIN

	DELETE FROM USUARIO_TELEFONE
    WHERE CD_USUARIO = @CD_USUARIO;

    DELETE FROM USUARIO
    WHERE CD_USUARIO = @CD_USUARIO;
END;
